# Generated by Django 5.1.7 on 2025-03-31 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_product_category_remove_orderitem_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='name',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
    ]
